    plugins {
        id 'java'
        id 'org.springframework.boot' version '3.5.7'
        id 'io.spring.dependency-management' version '1.1.7'
    }

    group = 'com.sqc'
    version = '0.0.1-SNAPSHOT'
    description = 'Demo project for Spring Boot'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(22)
        }
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        // Web API
        implementation 'org.springframework.boot:spring-boot-starter-web'

        // Spring Data JPA
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

        // MySQL
        //implementation 'mysql:mysql-connector-java:8.0.34'
        implementation 'com.mysql:mysql-connector-j'


        // Lombok
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'

        // Mail
        implementation 'org.springframework.boot:spring-boot-starter-mail'

        // Thymeleaf
        implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

        // Flyway
        implementation 'org.flywaydb:flyway-core'
        implementation 'org.flywaydb:flyway-mysql'

        // Testing
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

        //cloudinary
        implementation 'com.cloudinary:cloudinary-http44:1.39.0'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
